package com.github.ars_affinity.perk;

public enum AffinityPerkType {
    PASSIVE_DOUSED,
    PASSIVE_DEHYDRATED,
    PASSIVE_BURIED,
    PASSIVE_GROUNDED,
    PASSIVE_SUMMON_HEALTH,
    PASSIVE_LICH_FEAST,
    PASSIVE_MANA_TAP,
    PASSIVE_MOB_PACIFICATION,
    PASSIVE_FIRE_THORNS,
    PASSIVE_HEALING_AMPLIFICATION,
    PASSIVE_REVERBERATION
} 