package com.github.ars_affinity.perk;

public enum AffinityPerkType {
    // REMOVED NEGATIVE PERKS - These are no longer needed in the new system
    // PASSIVE_DOUSED,        // Inhibits mana regeneration in rain/water
    // PASSIVE_DEHYDRATED,    // Inhibits mana regeneration in Nether/on fire
    // PASSIVE_BURIED,        // Inhibits mana regeneration deep underground
    // PASSIVE_GROUNDED,      // Inhibits mana regeneration when not touching ground
    // PASSIVE_BLIGHTED,      // Healing spells less effective and add nausea
    // PASSIVE_PACIFIST,      // Spell power reduction
    // PASSIVE_MANIPULATION_SICKNESS, // Sickness and hunger effects
    
    // POSITIVE PASSIVE PERKS
    PASSIVE_SUMMON_HEALTH,
    PASSIVE_SUMMONING_POWER,
    PASSIVE_SUMMON_DEFENSE,
    PASSIVE_LICH_FEAST,
    PASSIVE_MANA_TAP,
    PASSIVE_FIRE_THORNS,
    PASSIVE_HEALING_AMPLIFICATION,
    PASSIVE_FREE_JUMP,
    PASSIVE_DEFLECTION,
    PASSIVE_STONE_SKIN,
    PASSIVE_UNSTABLE_SUMMONING,
    PASSIVE_GHOST_STEP,
    PASSIVE_SOULSPIKE,
    PASSIVE_HYDRATION,
    PASSIVE_COLD_WALKER,
    PASSIVE_ROTTING_GUISE,
    
    // SCHOOL POWER PERKS
    PASSIVE_ABJURATION_POWER,
    PASSIVE_AIR_POWER,
    PASSIVE_EARTH_POWER,
    PASSIVE_FIRE_POWER,
    PASSIVE_MANIPULATION_POWER,
    PASSIVE_ANIMA_POWER,
    PASSIVE_WATER_POWER,
    
    // SCHOOL RESISTANCE PERKS
    PASSIVE_ABJURATION_RESISTANCE,
    PASSIVE_CONJURATION_RESISTANCE,
    PASSIVE_AIR_RESISTANCE,
    PASSIVE_EARTH_RESISTANCE,
    PASSIVE_FIRE_RESISTANCE,
    PASSIVE_MANIPULATION_RESISTANCE,
    PASSIVE_ANIMA_RESISTANCE,
    PASSIVE_WATER_RESISTANCE,
    
    // ACTIVE ABILITIES
    ACTIVE_GROUND_SLAM,
    ACTIVE_ICE_BLAST,
    ACTIVE_FIRE_DASH,
    ACTIVE_AIR_DASH,
    ACTIVE_GHOST_STEP,
    ACTIVE_CURSE_FIELD,
    ACTIVE_SANCTUARY,
    ACTIVE_SWAP_ABILITY,
    ACTIVE_SWARM,
} 