# Test Glyph Blacklist Configuration
# This file contains example blacklisted glyphs for testing the feature
# 
# WARNING: This is for testing only. In production, use the main config file.

[glyph_blacklist]
# Example blacklisted glyphs for testing
blacklistedGlyphs = [
    "ars_nouveau:effect_heal",
    "ars_nouveau:method_touch",
    "ars_elemental:effect_charm",
    "ars_nouveau:effect_light",
    "ars_nouveau:effect_glow"
]